name: CD

on:
  workflow_dispatch:
    inputs:
      versionName:
        description: "Specify version name"
        required: true
        type: string
jobs:
  build-and-deploy:
    name: Deploy App
    permissions:
      contents: "read"
      id-token: "write"
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v1"
        with:
          workload_identity_provider: ${{ secrets.DEV_GOOGLE_AUTH_WIP }}
          service_account: ${{ secrets.DEV_GOOGLE_AUTH_SA }}

      - id: "secrets"
        name: "Get Secret Manager Secrets"
        uses: "google-github-actions/get-secretmanager-secrets@v1"
        with:
          secrets: |-
            gcp_project_id:apolo11-dev/GCP_PROJECT_ID
            common_env:apolo11-dev/COMMON_ENV_FILE

      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          architecture: "x64"
          cache: "pip"

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Set Env Vars
        working-directory: ./apiserver/ix/config
        run: |
          echo "${{ steps.secrets.outputs.common_env }}" | base64 -d > common.env

      - name: Install dependencies
        working-directory: ./apiserver
        run: pip install -r requirements.txt

      - name: Deploy App Engine
        uses: "google-github-actions/deploy-appengine@v1"
        with:
          version: ${{ inputs.versionName }}
          promote: false
          working_directory: ./apiserver
          deliverables: app.yaml
          project_id: ${{ steps.secrets.outputs.gcp_project_id }}