
runtime: python311 # or another supported version

instance_class: F2
service: insurance-portal-backend

entrypoint: gunicorn -b :8081 -w 2 -t 90 --worker-class=gevent --worker-connections=1000 --max-requests=500 --max-requests-jitter=50 main:app

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 0
  max_instances: 100
  min_pending_latency: 30ms
  max_pending_latency: automatic
  max_concurrent_requests: 50